name: tests

on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  ARCHIVE_DIR: /tmp

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Show go version
      run: go version
    - name: Install deps
      run: make deps
    - name: Lint
      run: make check
    - name: Prepare machine
      run: sudo bash -e .github/machinesetup.sh
    - name: Compile driver
      run: make build
    - name: Produce OCI and Docker archives
      run: |
        sudo podman pull alpine:latest
        sudo podman save --format docker-archive --output $ARCHIVE_DIR/docker-archive alpine:latest
        sudo podman save --format oci-archive --output $ARCHIVE_DIR/oci-archive alpine:latest
        sudo podman image rm alpine:latest
    - name: Run Tests
      run: sudo -E GOPATH=$PWD/build CI=1 build/bin/gotestsum --junitfile build/test/result.xml -- -timeout=15m . ./api
    - name: Archive test result
      uses: actions/upload-artifact@v1
      with:
        name: test-result
        path: build/test/result.xml
